# Server Configuration
server.port=8080

# Spring Data Redis Configuration
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

# Cache Configuration (TTL 1 hour = 3600000 ms)
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000
